// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfZUtHAWMtX-qIULVGucbq9AJopSjNElU',
    appId: '1:712912716008:android:53aa5f5bfea7c691e7095d',
    messagingSenderId: '712912716008',
    projectId: 'todo-list-provider-55b7d',
    storageBucket: 'todo-list-provider-55b7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG601JIo64oGCbwiYnv2XUdb86urBF0JQ',
    appId: '1:712912716008:ios:1c8d89b9f07f0330e7095d',
    messagingSenderId: '712912716008',
    projectId: 'todo-list-provider-55b7d',
    storageBucket: 'todo-list-provider-55b7d.appspot.com',
    androidClientId: '712912716008-7dkmack9r2rtbr7quuc6dubtckf783l0.apps.googleusercontent.com',
    iosClientId: '712912716008-mt0djulf61e86jgutbr7ae1pv16i9rcd.apps.googleusercontent.com',
    iosBundleId: 'br.com.etflutter.adfTodoListProvider',
  );
}
